roleGos: YOUR_ROLE_GOS
botToken: YOUR_BOT_TOKEN
roleMain: YOUR_ROLE_MAIN
infoChannel: YOUR_INFO_CHANNEL
rvId: YOUR_RV_ID
gosguildId: YOUR_GOS_GUILD_ID
guildId: YOUR_GUILD_ID
appId: YOUR_APP_ID
ruleChannel: YOUR_RULE_CHANNEL
